/* Sample catalog. The same five ads, in the same shape, live in ../ads.json. */
window.CATALOG = [
  {
    id: "harbor-and-rye",
    businessName: "Harbor & Rye",
    tagline: "Cocktails and a late kitchen on the water.",
    image: "assets/ads/harbor-and-rye.svg",
    qr: "assets/qr/harbor-and-rye.svg",
    infoUrl: "https://harbor-and-rye.example",
    eyebrow: "Ballard",
    lines: ["Stay for", "the last call."],
    tone: "dark",
    panel: "#0c1b2e",
    ink: "#f4efe4",
    muted: "#b7c3d1",
    accent: "#e0b15c",
    scan: "Scan for the menu",
  },
  {
    id: "northline-eats",
    businessName: "Northline Eats",
    tagline: "A bowl, a bun, and a window seat.",
    image: "assets/ads/northline-eats.svg",
    qr: "assets/qr/northline-eats.svg",
    infoUrl: "https://northline-eats.example",
    eyebrow: "Lunch and late",
    lines: ["A bowl, a bun,", "a window."],
    tone: "light",
    panel: "#f3e7d6",
    ink: "#2a2118",
    muted: "#6d5848",
    accent: "#d8613c",
    scan: "Scan for today's bowls",
  },
  {
    id: "lumen-hotel",
    businessName: "Lumen Hotel",
    tagline: "Rooms with the city at your feet.",
    image: "assets/ads/lumen-hotel.svg",
    qr: "assets/qr/lumen-hotel.svg",
    infoUrl: "https://lumen-hotel.example",
    eyebrow: "South Lake Union",
    lines: ["The city,", "one floor down."],
    tone: "dark",
    panel: "#141c2e",
    ink: "#f6f1e8",
    muted: "#c5c0b4",
    accent: "#e39a6b",
    scan: "Scan for rooms",
  },
  {
    id: "pike-street-books",
    businessName: "Pike Street Books",
    tagline: "New fiction, staff picks, open late.",
    image: "assets/ads/pike-street-books.svg",
    qr: "assets/qr/pike-street-books.svg",
    infoUrl: "https://pike-street-books.example",
    eyebrow: "Pike Street",
    lines: ["For people", "who still read."],
    tone: "dark",
    panel: "#14281f",
    ink: "#f3ecdf",
    muted: "#c5d0c6",
    accent: "#e4c56a",
    scan: "Scan for the shelf",
  },
  {
    id: "cedar-dental",
    businessName: "Cedar Dental",
    tagline: "Cleanings, calm, and a chair with a view.",
    image: "assets/ads/cedar-dental.svg",
    qr: "assets/qr/cedar-dental.svg",
    infoUrl: "https://cedar-dental.example",
    eyebrow: "Capitol Hill",
    lines: ["Cleanings", "this week."],
    tone: "light",
    panel: "#f3f0e8",
    ink: "#1c342c",
    muted: "#5c6b64",
    accent: "#3e6b52",
    scan: "Scan to book",
  },
];

/* A made-up week of tablet traffic, so the desk is not empty before this browser plays an ad. */
window.SAMPLE = {
  impressions: {
    "harbor-and-rye": 486,
    "northline-eats": 402,
    "lumen-hotel": 311,
    "pike-street-books": 274,
    "cedar-dental": 198,
  },
  scans: {
    "harbor-and-rye": 41,
    "northline-eats": 28,
    "lumen-hotel": 19,
    "pike-street-books": 33,
    "cedar-dental": 14,
  },
};
